#!/usr/bin/env ruby
# frozen_string_literal: true

require 'minitest/autorun'
require 'tempfile'
require 'fileutils'

require_relative '../scripts/transform-formula'

class HoistMethodsTest < Minitest::Test
  def setup
    @processor = FormulaProcessor.new
  end

  def test_hoists_nested_install_method
    input = <<~RUBY
      # This file was generated by GoReleaser
      class Coop < Formula
        desc "Test formula"
        homepage "https://example.com"

        on_macos do
          on_arm do
            url "https://example.com/darwin-arm64.tar.gz"
            sha256 "abc123"

            def install
              bin.install "coop"
            end
          end

          on_intel do
            url "https://example.com/darwin-amd64.tar.gz"
            sha256 "def456"

            def install
              bin.install "coop"
            end
          end
        end

        on_linux do
          on_arm do
            url "https://example.com/linux-arm64.tar.gz"
            sha256 "ghi789"

            def install
              bin.install "coop"
            end
          end
        end
      end
    RUBY

    result = process_string(input)

    # Should have def install at class level (2-space indent)
    assert_match(/^  def install\b/, result, 'install should be at class level')

    # Should NOT have nested def install
    refute_match(/^      def install\b/, result, 'should not have nested install')

    # Should still have on_macos blocks with url/sha256
    assert_match(/on_macos/, result)
    assert_match(/url\(?["']https:/, result)  # unparser may use url(...) or url "..."
  end

  def test_hoists_test_and_caveats_methods
    input = <<~RUBY
      # This file was generated by GoReleaser
      class Foo < Formula
        on_macos do
          on_arm do
            url "https://example.com/foo.tar.gz"
            sha256 "abc"

            def install
              bin.install "foo"
            end

            def test
              system bin/"foo", "--version"
            end

            def caveats
              "Remember to configure"
            end
          end
        end
      end
    RUBY

    result = process_string(input)

    assert_match(/^  def install\b/, result)
    assert_match(/^  def test\b/, result)
    assert_match(/^  def caveats\b/, result)
  end

  def test_skips_non_goreleaser_formula
    input = <<~RUBY
      class Manual < Formula
        desc "Manually written"

        on_macos do
          def install
            bin.install "manual"
          end
        end
      end
    RUBY

    result = process_string(input)

    # Should be unchanged (no processing)
    assert_nil result
  end

  def test_skips_already_hoisted_formula
    input = <<~RUBY
      # This file was generated by GoReleaser
      class Already < Formula
        on_macos do
          url "https://example.com/already.tar.gz"
          sha256 "abc"
        end

        def install
          bin.install "already"
        end
      end
    RUBY

    result = process_string(input)

    # Should be unchanged (already correct)
    assert_nil result
  end

  def test_preserves_header_comments
    input = <<~RUBY
      # This file was generated by GoReleaser
      # typed: false
      # frozen_string_literal: true

      class Coop < Formula
        on_macos do
          on_arm do
            url "https://example.com/coop.tar.gz"
            sha256 "abc"

            def install
              bin.install "coop"
            end
          end
        end
      end
    RUBY

    result = process_string(input)

    assert result.start_with?('# This file was generated by GoReleaser')
    assert_match(/# typed: false/, result)
    assert_match(/# frozen_string_literal: true/, result)
  end

  def test_removes_empty_blocks
    input = <<~RUBY
      # This file was generated by GoReleaser
      class Coop < Formula
        on_macos do
          on_arm do
            def install
              bin.install "coop"
            end
          end
        end
      end
    RUBY

    result = process_string(input)

    # Empty on_arm block should be removed
    refute_match(/on_arm do\s*end/, result)
  end

  private

  def process_string(input)
    file = Tempfile.new(['formula', '.rb'])
    begin
      file.write(input)
      file.close

      # Capture whether processing happened
      original = File.read(file.path)
      @processor.process(file.path)
      processed = File.read(file.path)

      # Return nil if unchanged, otherwise return result
      original == processed ? nil : processed
    ensure
      file.unlink
    end
  end
end
