#!/usr/bin/env ruby
# frozen_string_literal: true

require 'minitest/autorun'
require 'tempfile'
require 'fileutils'
require 'stringio'

require_relative '../scripts/transform-formula'

class HoistMethodsTest < Minitest::Test
  def setup
    @processor = FormulaProcessor.new
  end

  def test_hoists_nested_install_method
    input = <<~RUBY
      # This file was generated by GoReleaser
      class Coop < Formula
        desc "Test formula"
        homepage "https://example.com"

        on_macos do
          on_arm do
            url "https://example.com/darwin-arm64.tar.gz"
            sha256 "abc123"

            def install
              bin.install "coop"
            end
          end

          on_intel do
            url "https://example.com/darwin-amd64.tar.gz"
            sha256 "def456"

            def install
              bin.install "coop"
            end
          end
        end

        on_linux do
          on_arm do
            url "https://example.com/linux-arm64.tar.gz"
            sha256 "ghi789"

            def install
              bin.install "coop"
            end
          end
        end
      end
    RUBY

    result = process_string(input)

    # Should have def install at class level (2-space indent)
    assert_match(/^  def install\b/, result, 'install should be at class level')

    # Should NOT have nested def install
    refute_match(/^      def install\b/, result, 'should not have nested install')

    # Should still have on_macos blocks with url/sha256
    assert_match(/on_macos/, result)
    assert_match(/url\(?["']https:/, result)  # unparser may use url(...) or url "..."
  end

  def test_hoists_test_and_caveats_methods
    input = <<~RUBY
      # This file was generated by GoReleaser
      class Foo < Formula
        on_macos do
          on_arm do
            url "https://example.com/foo.tar.gz"
            sha256 "abc"

            def install
              bin.install "foo"
            end

            def test
              system bin/"foo", "--version"
            end

            def caveats
              "Remember to configure"
            end
          end
        end
      end
    RUBY

    result = process_string(input)

    assert_match(/^  def install\b/, result)
    assert_match(/^  def test\b/, result)
    assert_match(/^  def caveats\b/, result)
  end

  def test_skips_non_goreleaser_formula
    input = <<~RUBY
      class Manual < Formula
        desc "Manually written"

        on_macos do
          def install
            bin.install "manual"
          end
        end
      end
    RUBY

    result = process_string(input)

    # Should be unchanged (no processing)
    assert_nil result
  end

  def test_skips_already_hoisted_formula
    input = <<~RUBY
      # This file was generated by GoReleaser
      class Already < Formula
        on_macos do
          url "https://example.com/already.tar.gz"
          sha256 "abc"
        end

        def install
          bin.install "already"
        end
      end
    RUBY

    result = process_string(input)

    # Should be unchanged (already correct)
    assert_nil result
  end

  def test_preserves_header_comments
    input = <<~RUBY
      # This file was generated by GoReleaser
      # typed: false
      # frozen_string_literal: true

      class Coop < Formula
        on_macos do
          on_arm do
            url "https://example.com/coop.tar.gz"
            sha256 "abc"

            def install
              bin.install "coop"
            end
          end
        end
      end
    RUBY

    result = process_string(input)

    assert result.start_with?('# This file was generated by GoReleaser')
    assert_match(/# typed: false/, result)
    assert_match(/# frozen_string_literal: true/, result)
  end

  def test_removes_empty_blocks
    input = <<~RUBY
      # This file was generated by GoReleaser
      class Coop < Formula
        on_macos do
          on_arm do
            def install
              bin.install "coop"
            end
          end
        end
      end
    RUBY

    result = process_string(input)

    # Empty on_arm block should be removed
    refute_match(/on_arm do\s*end/, result)
  end

  def test_methods_output_in_config_order
    # Methods appear in reverse order in source (caveats, test, install)
    # but should be output in config order (install, test, caveats)
    input = <<~RUBY
      # This file was generated by GoReleaser
      class Foo < Formula
        on_macos do
          on_arm do
            url "https://example.com/foo-arm.tar.gz"
            sha256 "abc"

            def caveats
              "Remember to configure"
            end
          end

          on_intel do
            url "https://example.com/foo-intel.tar.gz"
            sha256 "def"

            def test
              system bin/"foo", "--version"
            end
          end
        end

        on_linux do
          on_arm do
            url "https://example.com/foo-linux.tar.gz"
            sha256 "ghi"

            def install
              bin.install "foo"
            end
          end
        end
      end
    RUBY

    result = process_string(input)

    # Find positions of each method at class level
    install_pos = result.index(/^  def install\b/)
    test_pos = result.index(/^  def test\b/)
    caveats_pos = result.index(/^  def caveats\b/)

    assert install_pos, 'install method should exist at class level'
    assert test_pos, 'test method should exist at class level'
    assert caveats_pos, 'caveats method should exist at class level'

    # Methods should be in config order: install < test < caveats
    assert install_pos < test_pos, 'install should come before test'
    assert test_pos < caveats_pos, 'test should come before caveats'
  end

  def test_reorders_test_do_block_after_def_install
    # GoReleaser generates test do block before def install
    # brew audit --strict requires install before test
    input = <<~RUBY
      # This file was generated by GoReleaser
      class Hamsign < Formula
        desc "CLI tools"
        homepage "https://example.com"

        on_macos do
          url "https://example.com/darwin.tar.gz"
          sha256 "abc123"
        end

        test do
          system bin/"tool", "--help"
        end

        def install
          bin.install "tool"
        end
      end
    RUBY

    result = process_string(input)

    # Find positions of install and test at class level
    install_pos = result.index(/^  def install\b/)
    test_pos = result.index(/^  test \{/) || result.index(/^  test do\b/)

    assert install_pos, 'def install should exist at class level'
    assert test_pos, 'test block should exist at class level'

    # install must come before test (brew audit requirement)
    assert install_pos < test_pos, 'install should come before test do block'
  end

  def test_warns_on_missing_version
    # Formula missing version attribute should trigger warning
    input = <<~RUBY
      # This file was generated by GoReleaser
      class Foo < Formula
        desc "Test"
        homepage "https://example.com"

        on_macos do
          on_arm do
            def install
              bin.install "foo"
            end
          end
        end
      end
    RUBY

    warnings = capture_stderr { process_string(input) }

    assert_match(/missing.*version.*url/i, warnings, 'should warn about missing version/url')
  end

  def test_no_warning_with_version
    input = <<~RUBY
      # This file was generated by GoReleaser
      class Foo < Formula
        desc "Test"
        homepage "https://example.com"
        version "1.0.0"

        on_macos do
          on_arm do
            def install
              bin.install "foo"
            end
          end
        end
      end
    RUBY

    warnings = capture_stderr { process_string(input) }

    refute_match(/missing.*version/i, warnings, 'should not warn when version present')
  end

  def test_no_warning_with_url
    input = <<~RUBY
      # This file was generated by GoReleaser
      class Foo < Formula
        desc "Test"
        homepage "https://example.com"

        on_macos do
          on_arm do
            url "https://example.com/foo.tar.gz"
            sha256 "abc123"

            def install
              bin.install "foo"
            end
          end
        end
      end
    RUBY

    warnings = capture_stderr { process_string(input) }

    refute_match(/missing.*version/i, warnings, 'should not warn when url present')
  end

  private

  def capture_stderr
    original_stderr = $stderr
    $stderr = StringIO.new
    yield
    $stderr.string
  ensure
    $stderr = original_stderr
  end

  def process_string(input)
    file = Tempfile.new(['formula', '.rb'])
    begin
      file.write(input)
      file.close

      # Capture whether processing happened
      original = File.read(file.path)
      @processor.process(file.path)
      processed = File.read(file.path)

      # Return nil if unchanged, otherwise return result
      original == processed ? nil : processed
    ensure
      file.unlink
    end
  end
end
