.PHONY: test install integration clean push hooks lint help

help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "Targets:"
	@echo "  test         Run unit tests"
	@echo "  integration  Run end-to-end transformation test"
	@echo "  all          Run all tests"
	@echo "  lint         Run rubocop linter"
	@echo "  install      Install Ruby dependencies"
	@echo "  hooks        Install git hooks"
	@echo "  push         Run tests, commit, and push (m='message')"
	@echo "  clean        Remove temp files"
	@echo "  help         Show this help"

test: install
	ruby test/transform_formula_test.rb

lint: install
	rubocop scripts/transform-formula.rb test/transform_formula_test.rb --only Style,Lint || true

install:
	@command -v ruby >/dev/null || (echo "Ruby required" && exit 1)
	@gem list -i parser >/dev/null 2>&1 || gem install parser
	@gem list -i unparser >/dev/null 2>&1 || gem install unparser
	@gem list -i minitest >/dev/null 2>&1 || gem install minitest
	@gem list -i rubocop >/dev/null 2>&1 || gem install rubocop

hooks:
	git config core.hooksPath .githooks
	@echo "Git hooks installed"

integration: install
	@mkdir -p /tmp/homebrew-transform-test/Formula
	@printf '%s\n' \
		'# typed: false' \
		'# frozen_string_literal: true' \
		'# This file was generated by GoReleaser. DO NOT EDIT.' \
		'class Test < Formula' \
		'  desc "Test formula"' \
		'  homepage "https://example.com"' \
		'  on_macos do' \
		'    if Hardware::CPU.arm?' \
		'      url "https://example.com/test.tar.gz"' \
		'      sha256 "abc123"' \
		'      def install' \
		'        bin.install "test"' \
		'      end' \
		'    end' \
		'  end' \
		'end' > /tmp/homebrew-transform-test/Formula/test.rb
	ruby scripts/transform-formula.rb /tmp/homebrew-transform-test/Formula/test.rb
	rubocop --autocorrect --only Style/BlockDelimiters /tmp/homebrew-transform-test/Formula/test.rb 2>/dev/null || true
	@echo "=== Transformed formula ==="
	@cat /tmp/homebrew-transform-test/Formula/test.rb
	@echo ""
	@grep -qE '^  def install' /tmp/homebrew-transform-test/Formula/test.rb && echo "✓ def install at class level"
	@! grep -qE '^      def install' /tmp/homebrew-transform-test/Formula/test.rb && echo "✓ No nested def install"
	@rm -rf /tmp/homebrew-transform-test

clean:
	rm -rf /tmp/homebrew-transform-test

push: test
	git add -A
	git commit -m "$(or $(m),Initial commit)" || true
	git push -u origin main

all: test integration
